1-run_inline

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,2 +1,10 @@
 #!/bin/bash
-python3 -c  “$PYCODE”
+
+# Check if the environment variable $PYCODE is set
+if [ -z "$PYCODE" ]; then
+    echo "Error: Environment variable \$PYCODE is not set."
+    exit 1
+fi
+
+# Run the Python code
+python3 -c "$PYCODE"
